### ISSUE TITLE
I'm getting the following compiler error when trying to use Assimp.

### ISSUE THREAD

**Issue by WhatMeWorry** [Sobaya007/bindbc-assimp#1]
..\..\..\AppData\Local\dub\packages\bindbc-assimp-0.0.1\bindbc-assimp\source\bindbc\assimp\types.d(3,8): Error: module `std` is in file 'std.d' which cannot be read
import path[0] = ..\..\..\AppData\Local\dub\packages\bindbc-assimp-0.0.1\bindbc-assimp\source
import path[1] = ..\..\..\AppData\Local\dub\packages\bindbc-loader-0.2.1\bindbc-loader\source
import path[2] = C:\ldc2\bin\..\import
FAIL ..\..\..\AppData\Local\dub\packages\bindbc-assimp-0.0.1\bindbc-assimp\.dub\build\dynamic-debug-windows-x86_64-ldc_2084-33243A6FCBA72BCCBDE19ED54801ADA2\ BindBC_Assimp staticLibrary
ldc2 failed with exit code 1.
.\..\duball exited with code 2

**Comment by Sobaya007** [comment]
Thank you for reporting.
This library can be used with DMD >= 2.086.1 or LDC >= 1.16.0.
Please try after upgrading your compiler.
